import Head from "next/head"

export default function head() {
    return (
        <Head>
            <title>Super Mensa Evolution</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/SMELogo.png" />
        </Head>
    )
}